env: local
server:
  port: 8080
  servlet:
    context-path: /demo-consumer
spring:
  profiles:
    active: local
  # Spring boot application
  application:
    name: demo-consumer

# dubbo
dubbo:
  application:
    name: ${spring.application.name}
    owner: test
    environment: test
    qos-enable: true # 是否启动QoS
    qos-port: 33333 # 启动QoS绑定的端口
    qos-accept-foreign-ip: false # 是否允许远程访问
  # 注册中心配置, 默认zookeeper
  registry:
    id: nacos
    address: nacos://127.0.0.1:8848/?backup=127.0.0.1:8849,127.0.0.1:8850&username=${dubbo.registry.username}&password=${dubbo.registry.password} # 注册中心地址
    username: nacos
    password: nacos
    parameters:
      namespace: acb757f5-7564-4c16-8fef-8337ae86d217 # nacos命名空间, 默认public
  # 协议配置
  protocol:
    name: dubbo
    port: 20880 # dubbo协议暴露服务的端口
    threads: 500
    dispatcher: message
  # 消费者配置
  consumer:
    filter: dubboConsumerFilter
    init: true
    check: true
    timeout: 200
    retries: 1
  # 接口配置
  simple-service:
    version: 1.0.0
    group: test
